### ISSUE TITLE
4 Branch is missing when I fork

### ISSUE THREAD

**Issue by alvynstar** [linuxacademy/devops-essentials-sample-app#954]
I recently fork the repo and the 4 branch is missing.

**Comment by alvynstar** [comment]
ONly to find that by default the master branch is the only one to be copied

**Comment by rwalimbe26** [comment]
I can also see only one branch i.e. master

**Comment by alvynstar** [comment]
delete the repo and fork it again. uncheck the box that says copy only the master branch so you have 4 branch in your repo
